# Conda environment for machine learning

# Usage:
# conda env create -f machine-learning-environment.yml
# conda activate machine-learning
# conda list

name: machine-learning

channels:
  - conda-forge

dependencies:
- python
- numpy
- scikit-learn
- matplotlib
- jupyterlab


# References
# - https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually